name: Build blocklists (all)

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    paths:
      - '**/*.txt'
      - '**/compile-config.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cfg:
          - path: "Malvertising_Blocklist/compile-config.json"
            out:  "Malvertising_Blocklist/malvertising_blocklist.txt"
          - path: "Tracking_blocklist/compile-config.json"
            out:  "Tracking_blocklist/full_anti_track.txt"

    steps:
      - uses: actions/checkout@v4

      - run: npm i -g @adguard/hostlist-compiler

      - name: Compile ${{ matrix.cfg.path }}
        run: |
          hostlist-compiler \
             -c ${{ matrix.cfg.path }} \
             -o ${{ matrix.cfg.out }}

      - name: Commit & push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "MCS-Bot"
          if git diff --quiet ${{ matrix.cfg.out }}; then
            echo "No changes"
          else
            git add ${{ matrix.cfg.out }}
            git commit -m "Auto-build ${matrix.cfg.out} $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
          fi
