name: Compile and Publish All Blocklists

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - key: malvertising
            path: Malvertising_Blocklist/compile-config.json
            out:  Malvertising_Blocklist/malvertising_blocklist.txt
          - key: tracking
            path: Tracking_blocklist/compile-config.json
            out:  Tracking_blocklist/full_anti_track.txt
          - key: annoyances
            path: Annoyances_list/compile-config.json
            out: Annoyances_list/full_anti_track.txt
      max-parallel: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        uses: dcarbone/install-jq-action@v3
        with:
          version: "1.6"

      - name: Install hostlist-compiler
        run: npm install -g @adguard/hostlist-compiler

      - name: Compile preliminary output
        run: |
          hostlist-compiler -c "${{ matrix.cfg.path }}" -o "${{ matrix.cfg.out }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cfg.key }}
          path: |
            ${{ matrix.cfg.path }}
            ${{ matrix.cfg.out }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install jq
        uses: dcarbone/install-jq-action@v3
        with:
          version: '1.6'

      - name: Install hostlist-compiler
        run: npm install -g @adguard/hostlist-compiler

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Compare, bump version & recompile
        id: process
        run: |
          changed_any=false

          for dir in artifacts/*; do
            key=$(basename "$dir")
            cfg="$dir/compile-config.json"
            
            rel_out=$(jq -r '.out' "$cfg")
              # gebruik de matrix-mapping als reserve
              case "$key" in
                malvertising) rel_out="Malvertising_Blocklist/malvertising_blocklist.txt" ;;
                tracking)     rel_out="Tracking_blocklist/full_anti_track.txt" ;;
                annoyances)   rel_out="Annoyances_list/annoyances.txt" ;;
                *)            echo "::error::Geen out-pad voor key $key"; exit 1 ;;
              esac
            fi

            
            repo_out="$GITHUB_WORKSPACE/$rel_out"
            artifact_out="$dir/$rel_out"

            if [[ ! -f "$repo_out" ]]; then
              echo "::error::repo_out niet gevonden: $repo_out"
              exit 1
            fi
            if [[ ! -f "$artifact_out" ]]; then
              echo "::error::artifact_out niet gevonden: $artifact_out"
              exit 1
            fi

            if ! cmp -s "$artifact_out" "$repo_out"; then
              echo "🔄 $key changed"

              cur=$(jq -r '.version' "$cfg")
              [[ "$cur" == "auto" || -z "$cur" ]] && cur="1.0"
              IFS='.' read -r _ minor _ <<<"$cur"
              minor=$((minor + 1))
              new="1.${minor}"
              jq ".version = \"${new}\"" "$cfg" > "$cfg.tmp" && mv "$cfg.tmp" "$cfg"
              echo "Bumped $key to $new"

              hostlist-compiler -c "$cfg" -o "$repo_out"
              git add "$cfg" "$repo_out"
              changed_any=true
            else
              echo "✅ $key unchanged"
            fi
          done

          echo "changed_any=$changed_any" >> $GITHUB_OUTPUT

      - name: Cleanup temporary artifacts
        if: always()
        run: rm -rf artifacts

      - name: Commit & push if needed
        if: steps.process.outputs.changed_any == 'true'
        run: |
          git config user.email "actions@github.com"
          git config user.name "MCS-Bot"
          git commit -m "Auto-build updated blocklists – $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push --force-with-lease
