name: Compile and Publish All Blocklists

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - key: malvertising
            path: Malvertising_Blocklist/compile-config.json
            out:  Malvertising_Blocklist/malvertising_blocklist.txt
          - key: tracking
            path: Tracking_blocklist/compile-config.json
            out:  Tracking_blocklist/full_anti_track.txt
          - key: annoyances
            path: Annoyances_list/compile-config.json
            out: Annoyances_list/full_anti_track.txt
      max-parallel: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        uses: dcarbone/install-jq-action@v3
        with:
          version: "1.6"

      - name: Install hostlist-compiler
        run: npm install -g @adguard/hostlist-compiler

      - name: Compile preliminary output
        run: |
          hostlist-compiler -c "${{ matrix.cfg.path }}" -o "${{ matrix.cfg.out }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.cfg.key }}
          path: |
            ${{ matrix.cfg.path }}
            ${{ matrix.cfg.out }}

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install jq
        uses: dcarbone/install-jq-action@v3
        with:
          version: '1.6'

      - name: Install hostlist-compiler
        run: npm install -g @adguard/hostlist-compiler

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Compare, bump version & recompile
        id: process
        run: |
          changed_any=false

          for dir in artifacts/*; do
            key=$(basename "$dir")
            case "$key" in
              malvertising)
                cp "$dir/Malvertising_Blocklist/compile-config.json" "Malvertising_Blocklist/"
                cp "$dir/Malvertising_Blocklist/malvertising_blocklist.txt" "Malvertising_Blocklist/"
                artifact_cfg="Malvertising_Blocklist/compile-config.json"
                artifact_out="Malvertising_Blocklist/malvertising_blocklist.txt"
                ;;
              tracking)
                cp "$dir/Tracking_blocklist/compile-config.json" "Tracking_blocklist/"
                cp "$dir/Tracking_blocklist/full_anti_track.txt" "Tracking_blocklist/"
                artifact_cfg="Tracking_blocklist/compile-config.json"
                artifact_out="Tracking_blocklist/full_anti_track.txt"
                ;;
              annoyances)
                cp "$dir/Annoyances_list/compile-config.json" "Annoyances_list/"
                cp "$dir/Annoyances_list/full_anti_track.txt" "Annoyances_list/"
                artifact_cfg="Annoyances_list/compile-config.json"
                artifact_out="Annoyances_list/full_anti_track.txt"
                ;;
              *)
                exit 1
                ;;
            esac

            if ! git diff --quiet "$artifact_out" || ! git diff --quiet "$artifact_cfg"; then
              echo "🔄 $key changed"
              
              cur=$(jq -r '.version' "$artifact_cfg")
              [[ "$cur" == "auto" || -z "$cur" ]] && cur="1.0"
              IFS='.' read -r _ minor _ <<<"$cur"
              minor=$((minor + 1))
              new="1.${minor}"
              jq ".version = \"${new}\"" "$artifact_cfg" > "$artifact_cfg.tmp" && mv "$artifact_cfg.tmp" "$artifact_cfg"
              
              hostlist-compiler -c "$artifact_cfg" -o "$artifact_out"
              git add "$artifact_cfg" "$artifact_out"
              changed_any=true
            else
              echo "✅ $key unchanged"
            fi
          done

          echo "changed_any=$changed_any" >> $GITHUB_OUTPUT

      - name: Cleanup temporary artifacts
        if: always()
        run: rm -rf artifacts

      - name: Commit & push if needed
        if: steps.process.outputs.changed_any == 'true'
        run: |
          git config user.email "actions@github.com"
          git config user.name "MCS-Bot"
          git commit -m "Auto-build updated blocklists – $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push --force-with-lease
